import { describe,it,expect } from 'vitest';
import { createGame,dispatch,getLegalActions,assertInvariants } from './game';
import { legacyBoard } from '../tests/fixtures';
import { neighbors,key } from './hex';
import { startCombat } from './combat';
import { claimDecrees } from './content/decrees';
import { describeEvent } from './log';
function ready(){const s=createGame({automatic:false,content:false,seed:7,playerCount:3,board:legacyBoard()});s.phase='PLAYER_ACTION';s.activePlayerId='p1';s.players.p1.currentRat.position={q:-1,r:0};s.players.p2.currentRat.position={q:1,r:0};s.players.p3.currentRat.position={q:2,r:-2};s.players.p1.actionsRemaining=2;s.cat.position={q:0,r:0};startCombat(s,'cat',{q:-1,r:0},{q:0,r:0});s.combat!.stage='PUSHBACK';s.combat!.winnerId='p1';return s;}
describe('Cat push chains',()=>{
 it('offers an adjacent rival and starts neutral combat without extra Actions or movement rolls',()=>{const s=ready();expect(getLegalActions(s,'p1')).toContainEqual({type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:1,r:0}});const r=dispatch(s,{type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:1,r:0}});expect(r.combat).toMatchObject({attackerId:'cat',defenderId:'p2',origin:'cat_push',catPushWinnerId:'p1'});expect(r.players.p1.currentRat.position).toEqual({q:0,r:0});expect(r.combat!.attackerRoll).toHaveLength(4);expect(r.eventLog.filter(e=>e.type==='CAT_MOVED')).toHaveLength(0);assertInvariants(r);});
 it('lets the first winner choose Cat retreat when forward is blocked and origin occupied',()=>{const s=ready();s.board.hexes['2,0'].terrain='rock';let r=dispatch(s,{type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:1,r:0}});r.combat!.attackerRoll=[4];r.combat!.defenderRoll=[1];r=dispatch(r,{type:'CONFIRM_DODGE',playerId:'p2'});expect(r.combat!.stage).toBe('CAT_RETREAT');expect(getLegalActions(r,'p1').some(a=>a.type==='SELECT_PUSHBACK')).toBe(true);const a=getLegalActions(r,'p1').find(a=>a.type==='SELECT_PUSHBACK')!;r=dispatch(r,a);expect(r.cat.offBoard).toBe(false);assertInvariants(r);});
 it('rejects nonadjacent chain targets',()=>{expect(()=>dispatch(ready(),{type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:2,r:-2}})).toThrow();});
 it('allows the new defender to win and push the Cat again',()=>{let r=dispatch(ready(),{type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:1,r:0}});r.combat!.attackerRoll=[1];r.combat!.defenderRoll=[6];r=dispatch(r,{type:'CONFIRM_DODGE',playerId:'p2'});expect(r.combat!.winnerId).toBe('p2');expect(getLegalActions(r,'p2').some(a=>a.type==='SELECT_PUSHBACK')).toBe(true);assertInvariants(r);});
});
it('emits a named Decree claim with reward and original UI slot',()=>{const s=createGame({automatic:false,seed:7,playerCount:3,board:legacyBoard()});s.content!.decrees=['sangre'];s.content!.decreeDeck=[];s.players.p1.attacks=3;claimDecrees(s,'immediate');const e=s.eventLog.find(e=>e.type==='DECREE_CLAIMED');expect(e).toMatchObject({playerId:'p1',cardId:'sangre',reward:1,slot:0});expect(describeEvent(e!)).toContain('P1 completes I Want Blood');});

it('sends a surrounded chained defender to Cat spawn, resolving an occupied spawn without overlap',()=>{const s=ready();for(const h of neighbors({q:1,r:0})){if(key(h)!=='0,0')s.board.hexes[key(h)].terrain='rock';}let r=dispatch(s,{type:'SELECT_PUSHBACK',playerId:'p1',destination:{q:1,r:0}});r.combat!.attackerRoll=[4];r.combat!.defenderRoll=[1];r=dispatch(r,{type:'CONFIRM_DODGE',playerId:'p2'});expect(r.players.p2.currentRat.position).toEqual(r.cat.spawnPosition);expect(r.cat.position).toEqual({q:1,r:0});expect(r.players.p1.currentRat.position).not.toEqual(r.cat.spawnPosition);assertInvariants(r);});
